name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide detailed information about your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: I have read the [README.md](https://github.com/blackchoey/backend-agent-test/blob/main/README.md) and [CONTRIBUTING.md](https://github.com/blackchoey/backend-agent-test/blob/main/CONTRIBUTING.md)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: I have also considered...

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New algorithm implementation
        - Performance improvement
        - User interface enhancement
        - Documentation improvement
        - Developer tooling
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be helpful
      placeholder: |
        1. When using the binary search with...
        2. For educational purposes, it would help...
        3. In production scenarios...
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas on how this could be implemented? (Optional)
      placeholder: |
        This could be implemented by...
        - Adding a new method that...
        - Modifying the existing algorithm to...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I would be interested in implementing this feature myself
        - label: I would be willing to help test this feature
        - label: I can provide additional feedback and requirements

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/blackchoey/backend-agent-test/blob/main/CODE_OF_CONDUCT.md)
          required: true